function data = ReadLeafExcelData(workbookFile, sheetName, range)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   cell array.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   leaf = importfile('leaf.xlsx','Folha1','A2:B991');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/07/06 19:16:51

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = '';
end

%% Import the data
[~, ~, data] = xlsread(workbookFile, sheetName, range);
data(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),data)) = {''};

data(1,:) = []; % Remove titles
data(numel(data(:,2)),3) = {[]}; % Create a new column

for i = 1:numel(data(:,2)) %Separate species from subspecies
    split = strsplit(data{i,2},'_');
    data{i,3} = data{i,2};
    data{i,2} = split{1};
%     s = size(split);
%     if(s(2) > 1)
%         data{i,3} = split{2};
%     end
%     
%     if(s(2) > 2)
%         data{i,3} = split{3}
%     end
    split = [];
end